Feature/isabella/footer
Fraternity-Code/projeto-pratico-git-techninjas pull request #15
Opened 2022-10-17 17:21 UTC by BellsV

2022-10-17 19:45 UTC, tl-lucasestevam requested changes
Arrumar também os nomes das img

2022-10-17 19:45 UTC, tl-lucasestevam commented on index.html
> +              <a href="#Youtube" target="_blank"><img src="./assets/Vector(1).svg" alt="Desenho da logo do YouTube em rosa escuro"></a>
Usa uma ul ;)

```html
<ul>
  <li>
    <a href="#Twitter" target="_blank"><img src="./assets/Vector(2).svg" alt="Desenho da logo do Twitter em rosa escuro"></a>
  </li>
  <li>
    <a href="#Twitter" target="_blank"><img src="./assets/Vector(2).svg" alt="Desenho da logo do Twitter em rosa escuro"></a>
  </li>
</ul>
```

2022-10-17 20:40 UTC, GabriellCastro requested changes

2022-10-17 20:40 UTC, GabriellCastro commented on style.css
>  }
Colocar uma linha vazia no fim de cada arquivo.
por que ? resposta: https://pt.stackoverflow.com/questions/272449/por-que-inserir-uma-linha-em-branco-no-final-do-c%C3%B3digo

2022-10-18 15:19 UTC, tl-lucasestevam approved these changes
LGTM ;)

2022-10-18 23:21 UTC, GabriellCastro approved these changes

2022-10-18 23:24 UTC, merged