Feature/vinny/how work
Fraternity-Code/projeto-pratico-git-techninjas pull request #17
Opened 2022-10-18 19:13 UTC by VinnySoares12

2022-10-18 23:19 UTC, GabriellCastro approved these changes

2022-10-18 23:41 UTC, myckwilliam requested changes
A imagem `Blur effec.svg` pode dar problema por conta do espaçamento. É melhor remover o espaço do nome da imagem, acrescentando um traço. Mas ta muito bom :D.

2022-10-18 23:42 UTC, myckwilliam commented
Tomar cuidado também com as tags dos commits. `styles` não é para estilos de CSS e sim para mudança no estilo do código: Espaços, Qubras de linha e etc.

2022-10-19 18:41 UTC, myckwilliam approved these changes
Shoow!

2022-10-19 21:15 UTC, tl-lucasestevam approved these changes
LGTM ;)

2022-10-19 21:24 UTC, merged